### ISSUE TITLE
Failure when running `asdf list all nodejs` without recent bash installed, on macOS

### ISSUE THREAD

**Issue by adamfeldman** [asdf-vm/asdf-nodejs#199]
Possibly related to #195?

Environment: 
* macOS 11.1
* `asdf` v0.8.0 installed via Homebrew or Git
* User shell: zsh

## Problem
```bash
➜  ~ which bash
/bin/bash
➜  ~ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
```

```bash
➜  ~ asdf list all nodejs
/Users/adamfeldman/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 35: local: -A: invalid option
local: usage: local name[=value] ...
/Users/adamfeldman/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 51: Fermium: unbound variable
[**OUTPUT TRUNCATED FOR BREVITY**]
➜  ~ ~/.asdf/plugins/nodejs/bin/list-all nodejs
/Users/adamfeldman/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 35: local: -A: invalid option
local: usage: local name[=value] ...
/Users/adamfeldman/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 51: Fermium: unbound variable
15.0.0 15.0.1 15.1.0 15.2.0 15.2.1 15.3.0 15.4.0 15.5.0 15.5.1 15.6.0
```
## Solution
```bash
➜  ~ brew install bash
➜  ~ which bash
/usr/local/bin/bash
➜  ~ /usr/local/bin/bash --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin20.2.0)
```

```bash
➜  ~ ~/.asdf/plugins/nodejs/bin/list-all nodejs
0.1.14 [**OUTPUT TRUNCATED FOR BREVITY, worked exactly as-expected**] lts-fermium lts 15.0.0 15.0.1 15.1.0 15.2.0 15.2.1 15.3.0 15.4.0 15.5.0 15.5.1 15.6.0
➜  ~ asdf list all nodejs
[**OUTPUT TRUNCATED FOR BREVITY, worked exactly as-expected**]
```

**Comment by dlech** [comment]
I had to open a new terminal to get the new `bash` after installing from Homebrew.

**Comment by adamfeldman** [comment]
Also of note: `bash` is not a dependency..
* ...for `asdf` in Homebrew: https://formulae.brew.sh/formula/asdf
*  ...for any of the pre-install Homebrew dependencies listed in the [asdf install docs](https://asdf-vm.com/#/core-manage-asdf?id=install)
   * [coreutils](https://formulae.brew.sh/formula/coreutils)
   * [curl](https://formulae.brew.sh/formula/curl)
   * [git](https://formulae.brew.sh/formula/git)

**Comment by Boztown** [comment]
Thanks @adamfeldman. I had this issue on a brand new M1 MacBook and chalked it up at first to some of the ARM compatibility issues I expect to run into. Installing a newer version of Bash like you state worked for me as well.

I'm using Fish shell but probably wouldn't normally think to update Bash even if I used it as my primary shell.

**Comment by augustobmoura** [comment]
Yes it iis from #195


> Also of note: `bash` is not a dependency..
> 
> * ...for `asdf` in Homebrew: https://formulae.brew.sh/formula/asdf
> * ...for any of the pre-install Homebrew dependencies listed in the [asdf install docs](https://asdf-vm.com/#/core-manage-asdf?id=install)
>   
>   * [coreutils](https://formulae.brew.sh/formula/coreutils)
>   * [curl](https://formulae.brew.sh/formula/curl)
>   * [git](https://formulae.brew.sh/formula/git)

Bash is pretty much a implied dependency at this point, much of asdf core and asdf-nodejs depends on bash today. Maybe we should put that out in the docs in some way, together with the minimum version required.

Is too much to upgrade bash in MacOS today? I thought it was okay to use associative arrays because is a relative old version, since 4.0 from 2009 theoretically, also can you guys confirm the default bash version is prior to 4.0? We can revert the code to awk or try to work something out with older bash versions

**Comment by adamfeldman** [comment]
Thanks @augustobmoura! I'm sorry I wasn't explicit in my previous comment: I have no concern with `bash` as a dependency. 

As a Homebrew user on macOS, `brew` makes it painless to install `bash`. If it were documented as required, that would more than satisfy me :)

**Comment by adamfeldman** [comment]
I am not familiar with contributing to either asdf core or asdf-nodejs, if someone thinks it's appropriate I can open an issue with asdf core about making bash a dependency for the Homebrew formula.

**Comment by augustobmoura** [comment]
> Thanks @augustobmoura! I'm sorry I wasn't explicit in my previous comment: I have no concern with `bash` as a dependency. I didn't mean to sound like you should revert your efforts.

It's ok to revert the code if we impact more users, given that upgrading bash is straightforward (and I would guess even recommended for security purposes), I don't think is necessary to revert it then

> I am not familiar with contributing to either asdf core or asdf-nodejs, if someone thinks it's appropriate I can open an issue with asdf core about making bash a dependency for the Homebrew formula.

I'm not a core developer but I would guess opening a issue in https://github.com/asdf-vm/asdf discussing about putting the bash requirement in the docs and mentioning this thread would be a good first step

**Comment by anthonypillot** [comment]
Have same issue. On a MacBook Pro 16 inch.

And your workaround with installing `brew install bash` works fine too.

**Comment by Stratus3D** [comment]
I think we should fix this. Would using `declare -a aliases` instead of `local -a aliases` fix this problem? (see https://github.com/asdf-vm/asdf-nodejs/blob/master/lib/utils.sh#L35)

**Comment by Stratus3D** [comment]
If possible we should stick with what is POSIX complaint. It's not always possible but in this case I think it might be.

**Comment by augustobmoura** [comment]
> I think we should fix this. Would using `declare -a aliases` instead of `local -a aliases` fix this problem? (see https://github.com/asdf-vm/asdf-nodejs/blob/master/lib/utils.sh#L35)

Probably not, as associative arrays were added in 4.x, `local` is kinda a alias to `declare`

> If possible we should stick with what is POSIX complaint. It's not always possible but in this case I think it might be.

I will write a PR using a plain string instead of associative arrays

**Comment by mdwagner** [comment]
I'm having the same issue, with fish-shell as my default shell.

**Comment by Quezion** [comment]
Ran `brew install bash` today, didn't seem to fix the issue. asdf was installed via `brew install asdf`. M1 apple silicon mac on 12.0.1

```bash
$ which bash
/opt/homebrew/bin/bash

$ bash -version
GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)

$ asdf list-all erlang
No such plugin: erlang
```

Was trying to follow https://faun.pub/switch-easily-between-multiple-kubernetes-version-on-macos-9d61b9bc8287 , not sure of next solution

**Comment by augustobmoura** [comment]
> Ran `brew install bash` today, didn't seem to fix the issue. asdf was installed via `brew install asdf`. M1 apple silicon mac on 12.0.1

Did you update your `asdf-nodejs` plugin? Running `asdf update nodejs` should be enough.

I can't reproduce this error using bash 3, so I don't think it's related to just the bash version

**Comment by Quezion** [comment]
@augustobmoura Looks like that was it -- not related to bash, but rather ensuring this was setup & updated to begin with.

Awesome because ASDF is even more useful in this era of Apple silicon. Thank you 🙏
