### ISSUE TITLE
gpg: keyserver receive failed: No data

### ISSUE THREAD

**Issue by richstokes** [asdf-vm/asdf-nodejs#241]
Version `0.8.1`

Keep getting 
```
gpg: key 50A3051F888C628D: 1 signature not checked due to a missing key
gpg: key 50A3051F888C628D: public key "Julien Gilli <jgilli@fastmail.fm>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No name
gpg: key 7D33FF9D0246406D: 3 signatures not checked due to missing keys
gpg: key 7D33FF9D0246406D: public key "Timothy J Fontaine (Personal) <tjfontaine@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No data
gpg: keyserver receive failed: No data
gpg: keyserver receive failed: No data
gpg: keyserver receive failed: No data
```

When running `'${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-previous-release-team-keyring'`

On `Ubuntu 18.04.5 LTS`

**Comment by richstokes** [comment]
Seems intermittent, if I retry it a bunch of times it will eventually work

**Comment by richstokes** [comment]
Just tried with Ubuntu 20.04 LTS also in case it was an OS thing, didn't make any difference

**Comment by richstokes** [comment]
Looks like its probably related to https://github.com/asdf-vm/asdf-nodejs/pull/240

**Comment by richstokes** [comment]
It's now failing every time with

```
gpg: keyserver receive failed: No keyserver available
gpg: keyserver receive failed: No keyserver available
```

**Comment by Stratus3D** [comment]
@richstokes I have merged #240, please update asdf-nodejs and try again. `asdf plugin-update nodejs`.

**Comment by richstokes** [comment]
I updated it, same problem

**Comment by Stratus3D** [comment]
Does the error preventing you from importing the keys? I see the errors on my machine but they don't prevent the script from getting the keys from the other servers.

**Comment by Stratus3D** [comment]
This is an issue with the key servers not being available, not a bug in this plugin.

**Comment by amireldor** [comment]
It happens to me too and happened to me last time I tried about a month ago. I have the updated plugin. Some keys fail and some keys successfully import but the problem persists either way. I have to resort to `NODEJS_CHECK_SIGNATURES=no`.

Also, it's a bit unclear that there are two scripts, import-release-team-keyring and the import-previous-release-team-keyring script mentioned above. 🤷‍♂️

**Comment by augustobmoura** [comment]
You only need to import the keys once in a machine (once for each user using asdf actually). Why is this problem so recurring for you guys? Importing once allows you to install all versions without reimporting them. This is also why the script is split, really old versions of node were signed for different people than the current maintainers, if you are using any node version greater than 1.0.0 you shouldn't need to import the legavy keys

**Comment by amireldor** [comment]
The problem is probably with the key servers. I never managed to import all keys when I installed node 16.3.0 about a month ago, so I skipped the signatures checks. Yesterday I wanted to upgrade to 16.4.0 so I faced the same issue again :)

:facepalm: I forgot to mention something _very_ important. I use WSL, @richstokes , does that happen to you too on WSL?
I've just tried installing some version under my real Ubuntu machine and it seems that I have all the keys previously imported successfully. This issue might be WSL-only.

**Comment by richstokes** [comment]
I'm using ubuntu server. We do this as part of a CD process. It was failing nearly every time when I opened the issue, now its mostly fine. I think it may have been an intermittent issue with the keyservers. Would be nice if asdf/plugins had a more straightforward install process.

**Comment by benfalk** [comment]
Hey 👋 

Just recently installed `asdf` along with the default nodejs plugin and when I try to install any version of nodejs I get the following output:

```
gpg: keyserver receive failed: Network is unreachable
gpg: keyserver receive failed: No keyserver available
```

I get this message about ~40 times before it fails declaring it cannot install whichever version I try.

I installed asdf via `homebrew` and am on the the latest version of Big Sir.

```bash
asdf --version
# v0.8.1
```

```bash
asdf plugin update nodejs                                                                                                                                      
Updating nodejs to master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by richstokes** [comment]
That sounds ideal. The live key server is great in theory, but in practice seems to be pretty clunky and error prone.

**Comment by benfalk** [comment]
This suggestion worked for me! https://github.com/asdf-vm/asdf-nodejs/issues/192#issuecomment-797448073

Thanks for pointing me in the right direction @augustobmoura
