### ISSUE TITLE
Don't work reshim for NPM dependencies

### ISSUE THREAD

**Issue by Vmelnikoff** [asdf-vm/asdf-nodejs#257]
Describe the Bug
I install node 16.8.0, add a global dependency of lite-server, then install node 16.9.0, do reshim

Steps to Reproduce
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs 16.8.0
asdf global nodejs 16.8.0
user:~
└─ arrow_forward node -v
v16.8.0
user:~
└─ arrow_forward npm -v
7.21.0
npm i -g lite-server
user:~
└─ arrow_forward which lite-server
/home/user/.asdf/shims/lite-server

asdf install nodejs 16.9.0
asdf global nodejs 16.9.0
asdf reshim nodejs 16.9.0

user:~
└─ arrow_forward which lite-server
/home/user/.asdf/shims/lite-server
user:~
└─ arrow_forward lite-server
No preset version installed for command lite-server
Please install a version by running one of the following:

asdf install nodejs 16.9.0

or add one of the following versions in your config file at /home/user/.tool-versions
nodejs 16.8.0
user:~
└─ arrow_forward asdf install nodejs 16.9.0
nodejs 16.9.0 is already installed

Expected Behaviour
I expect that the lite-server will work in the new version of node without additional installation (using reshim).

Actual Behaviour
user:~
└─ arrow_forward lite-server
No preset version installed for command lite-server
Please install a version by running one of the following:

asdf install nodejs 16.9.0

or add one of the following versions in your config file at /home/user/.tool-versions
nodejs 16.8.0
user:~
└─ arrow_forward asdf install nodejs 16.9.0
nodejs 16.9.0 is already installed

P.s. When switching back to 16.8.0, everything works.

Environment
OS:
Linux user 5.11.0-34-generic #36-Ubuntu SMP Thu Aug 26 19:22:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/user/.asdf
asdf plugins affected (if relevant)
ASDF INSTALLED PLUGINS:
nodejs https://github.com/asdf-vm/asdf-nodejs.git

**Comment by CherryDT** [comment]
Same issue here:

```
david@CHE-T14S:~/proj/schromm-repairman-client (master)$ electron-builder --help
No preset version installed for command electron-builder
Please install a version by running one of the following:

asdf install nodejs 16.10.0

or add one of the following versions in your config file at /home/david/.tool-versions
nodejs 14.17.3
david@CHE-T14S:~/proj/schromm-repairman-client (master)$ asdf install nodejs 16.10.0
nodejs 16.10.0 is already installed
david@CHE-T14S:~/proj/schromm-repairman-client (master)$ asdf install nodejs 14.17.3
nodejs 14.17.3 is already installed
```

`asdf reshim nodejs` had no effect.

**Comment by M1kep** [comment]
@CherryDT @Vmelnikoff How many items do you have in your default-npm-packages file? If only one, can you try adding a newline to the end of the file. Not really sure if something changed.. But from what I can see, the current method of reading the default-npm-packages (https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/install#L323-L332) will ignore the last line of a file if does not have a trailing line feed. From what I've found online, read returns if it does not see a newline character. I've fixed it on my side, and will get a PR submitted shortly

Some references:
https://stackoverflow.com/a/65676358
https://stackoverflow.com/a/1521498

**Comment by CherryDT** [comment]
Issue is back, this time with `claudia`:

```
s/david/proj/map-poi-fetcher-lambda (master)$ claudia update
No preset version installed for command claudia
Please install a version by running one of the following:

asdf install nodejs 16.10.0

or add one of the following versions in your config file at 
nodejs 14.17.3
david@CHE-T14S:/mnt/c/Users/david/proj/map-poi-fetcher-lambda (master)$ asdf reshim claudia
No such plugin: claudia
david@CHE-T14S:/mnt/c/Users/david/proj/map-poi-fetcher-lambda (master)$ asdf reshim nodejs
david@CHE-T14S:/mnt/c/Users/david/proj/map-poi-fetcher-lambda (master)$ claudia update
No preset version installed for command claudia
Please install a version by running one of the following:

asdf install nodejs 16.10.0

or add one of the following versions in your config file at 
nodejs 14.17.3
david@CHE-T14S:/mnt/c/Users/david/proj/map-poi-fetcher-lambda (master)$ 
```

The message is entirely unhelpful.
